repos:
- repo: https://github.com/python/black
  rev: 19.3b0
  hooks:
  - id: black
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.1
  hooks:
  - id: flake8
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-yaml
  - id: trailing-whitespace
    exclude: .*\.md$
- repo: local
  hooks:
  - id: shell-lint
    name: Shell Syntax Check
    description: Check Shell Syntax on ALL staged files with user friendly messages and colors
    entry: .pre-commit-hooks/shell-lint.sh
    language: script
    types: [shell]