name: Verify release
on:
  push:
    branches:
      - release-prep

jobs:
  check-version-change:
    name: Check version change
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Setup python and install packages
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
          architecture: x64
      - name: Check version change
        run: |
          VERSION="$(sed -n -E "s/^version = \"(.+)\"/\1/p" pyproject.toml)"
          ! pip3 install esque==blork 2>&1 | grep -oE "${VERSION}($|,)"
  publish-to-devpi:
    name: Publish to devpi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Setup python and install packages
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
          architecture: x64
      - name: Prepare environment for test publish
        if: success()
        run: |
          pip install "poetry==1.0.0b3" devpi-server devpi "pluggy<1,>=0.12.0"
          devpi-server --serverdir=/tmp/devpi --init
          devpi-server --serverdir=/tmp/devpi --start
          scripts/wait-for-it.sh localhost:3141 -t 60
          devpi use http://localhost:3141
          devpi login root --password=
          devpi index -c root/stable bases=root/pypi volatile=True
          devpi user -m root password="root"
          mkdir -p ${HOME}/.esque
          poetry config repositories.devpi http://localhost:3141/root/stable/
          poetry config repositories.testpypi http://test.pypi.org/simple/
      - name: Publish to devpi
        if: success()
        run: |
          poetry build
          poetry publish --repository devpi --username root --password root
      - name: Test devpi release
        if: success()
        run: |
          ! which esque
          VERSION=$(sed -n -E "s/^version = \"(.+)\"/\1/p" pyproject.toml)
          pushd /tmp
          pip install -i http://localhost:3141/root/stable/ --timeout 60 esque
          esque --help
          CURRENT_VERSION=$(esque --version | awk '{print $3}')
          [[ ${CURRENT_VERSION} == ${VERSION} ]]
          popd
      - name: Publish to testpypi
        if: success()
        run: |
          sed -i -E "s/^version = \"(.+)\".*/version = \"\1-$(git rev-parse --short HEAD)\"/" pyproject.toml
          poetry publish --repository testpypi --username ${{ secrets.TEST_PYPI_USER }} --password root ${{ secrets.TEST_PYPI_PASSWORD }}